# Stage 1
FROM node:22-alpine AS frontend-builder

ARG APP_TITLE
ENV VITE_APP_TITLE=$APP_TITLE

WORKDIR /app
COPY frontend/package*.json frontend/vite.config.ts frontend/tsconfig.json frontend/tsconfig.node.json ./
RUN npm ci
COPY frontend ./
RUN npm run build

# Stage 2
FROM node:22-alpine
WORKDIR /app
COPY --from=frontend-builder /app/dist ./dist
COPY --from=frontend-builder /app/node_modules ./node_modules
COPY frontend/package*.json frontend/vite.config.ts frontend/tsconfig.json frontend/tsconfig.node.json ./
EXPOSE 4173
CMD ["npm", "run", "preview", "--", "--host", "0.0.0.0", "--port", "4173"]
